services:
  postgres:
    image: postgres:17
    container_name: krishiguard-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: krishiguard
      POSTGRES_PASSWORD: krishiguard_dev
      POSTGRES_DB: krishiguard

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
